### ISSUE TITLE
No resource tags are implemented or passable

### ISSUE THREAD

**Issue by chrischildresssg** [StratusGrid/terraform-aws-config-rules#9]
Feature Request

## Expected Behavior
"input_tags" variable is used to pass desired resource tags to the config_rule resource(s).

## Actual Behavior
No tags are applied to the config_rule resource(s), or other resources in the module.

**Comment by DJKaswa** [comment]
Feature added in [this PR](https://github.com/StratusGrid/terraform-aws-config-rules/pull/10). Closing this issue.
